packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@node-rs/argon2'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
