/**
 * DEMO CATALOGUE — illustrative data for development, QA and staging only.
 *
 * - All brands are fictional and marked "(demo)". No real trademarks are used.
 * - No reviews or ratings are seeded (ratings stay 0 until real customers review).
 * - `soldCount` values exist only to demonstrate the "Best sellers" ordering.
 * - Remove everything before launch: `pnpm db:seed:demo --remove`.
 *
 * Prices are in RUPEES here (converted to paise by the seed).
 */

export interface DemoCategory {
  slug: string;
  name: string;
  description?: string;
  featured?: boolean;
  /** lucide-static icon name used for the generated category image. */
  icon: string;
  children?: DemoCategory[];
}

export interface DemoVariant {
  name: string;
  options: Record<string, string>;
  mrp: number;
  price: number;
  stock: number;
}

export interface DemoProduct {
  name: string;
  category: string;
  brand: string;
  icon: string;
  short: string;
  highlights: string[];
  specs: [string, string][];
  variants: DemoVariant[];
  tax: 5 | 12 | 18 | 28;
  hsn: string;
  sold: number;
  daysAgo: number;
  featured?: boolean;
  warranty?: string;
  returnDays?: number;
}

export const DEMO_BRANDS = [
  {
    slug: 'voltix',
    name: 'Voltix',
    featured: true,
    about: 'Everyday smartphones, tablets and accessories.',
  },
  {
    slug: 'aurora-sound',
    name: 'Aurora Sound',
    featured: true,
    about: 'Earbuds, headphones and speakers tuned for Indian homes and commutes.',
  },
  { slug: 'pulsefit', name: 'PulseFit', featured: true, about: 'Smartwatches and fitness gear.' },
  {
    slug: 'kavya-threads',
    name: 'Kavya Threads',
    featured: true,
    about: 'Contemporary ethnic and casual wear.',
  },
  {
    slug: 'urban-stride',
    name: 'Urban Stride',
    featured: true,
    about: 'Comfortable shoes and casual essentials.',
  },
  {
    slug: 'rasoi-pro',
    name: 'Rasoi Pro',
    featured: true,
    about: 'Kitchen appliances and cookware for daily cooking.',
  },
  { slug: 'nestcraft', name: 'NestCraft', featured: false, about: 'Home décor and storage.' },
  {
    slug: 'sattva-naturals',
    name: 'Sattva Naturals',
    featured: true,
    about: 'Skin and hair care with simple ingredients.',
  },
  {
    slug: 'tarang-sports',
    name: 'Tarang Sports',
    featured: false,
    about: 'Yoga and fitness equipment.',
  },
] as const;

export const DEMO_CATEGORIES: DemoCategory[] = [
  {
    slug: 'electronics',
    name: 'Electronics',
    icon: 'Smartphone',
    featured: true,
    description: 'Smartphones, audio, wearables and accessories.',
    children: [
      {
        slug: 'mobiles-tablets',
        name: 'Mobiles & Tablets',
        icon: 'Smartphone',
        children: [
          { slug: 'smartphones', name: 'Smartphones', icon: 'Smartphone', featured: true },
          { slug: 'tablets', name: 'Tablets', icon: 'Tablet' },
        ],
      },
      {
        slug: 'audio',
        name: 'Audio',
        icon: 'Headphones',
        featured: true,
        children: [
          { slug: 'earbuds', name: 'Earbuds', icon: 'Headset' },
          { slug: 'headphones', name: 'Headphones', icon: 'Headphones' },
          { slug: 'speakers', name: 'Speakers', icon: 'Speaker' },
        ],
      },
      {
        slug: 'wearables',
        name: 'Wearables',
        icon: 'Watch',
        featured: true,
        children: [{ slug: 'smartwatches', name: 'Smartwatches', icon: 'Watch' }],
      },
      {
        slug: 'mobile-accessories',
        name: 'Mobile Accessories',
        icon: 'BatteryCharging',
        children: [
          { slug: 'power-banks', name: 'Power Banks', icon: 'BatteryCharging' },
          { slug: 'chargers-cables', name: 'Chargers & Cables', icon: 'Cable' },
        ],
      },
    ],
  },
  {
    slug: 'fashion',
    name: 'Fashion',
    icon: 'Shirt',
    featured: true,
    description: 'Everyday and ethnic wear, footwear and bags.',
    children: [
      {
        slug: 'men',
        name: 'Men',
        icon: 'Shirt',
        children: [
          { slug: 'mens-t-shirts', name: 'T-Shirts', icon: 'Shirt' },
          { slug: 'mens-shoes', name: 'Shoes', icon: 'Footprints' },
        ],
      },
      {
        slug: 'women',
        name: 'Women',
        icon: 'Sparkles',
        children: [
          { slug: 'kurtas', name: 'Kurtas', icon: 'Shirt', featured: true },
          { slug: 'handbags', name: 'Handbags', icon: 'ShoppingBag' },
        ],
      },
    ],
  },
  {
    slug: 'home-kitchen',
    name: 'Home & Kitchen',
    icon: 'CookingPot',
    featured: true,
    description: 'Appliances, cookware and décor for every home.',
    children: [
      { slug: 'kitchen-appliances', name: 'Kitchen Appliances', icon: 'Blend', featured: true },
      { slug: 'cookware', name: 'Cookware', icon: 'CookingPot' },
      { slug: 'home-decor', name: 'Home Décor', icon: 'Lamp' },
    ],
  },
  {
    slug: 'beauty',
    name: 'Beauty & Personal Care',
    icon: 'Sparkles',
    featured: true,
    description: 'Skincare and hair care essentials.',
    children: [
      { slug: 'skincare', name: 'Skincare', icon: 'Droplet' },
      { slug: 'hair-care', name: 'Hair Care', icon: 'Wind' },
    ],
  },
  {
    slug: 'sports-fitness',
    name: 'Sports & Fitness',
    icon: 'Dumbbell',
    featured: true,
    description: 'Gear for workouts, yoga and outdoor play.',
    children: [
      { slug: 'fitness-equipment', name: 'Fitness Equipment', icon: 'Dumbbell' },
      { slug: 'yoga', name: 'Yoga', icon: 'PersonStanding' },
    ],
  },
];

const v = (
  name: string,
  options: Record<string, string>,
  mrp: number,
  price: number,
  stock: number,
): DemoVariant => ({
  name,
  options,
  mrp,
  price,
  stock,
});

export const DEMO_PRODUCTS: DemoProduct[] = [
  // ---------------------------------------------------------------- smartphones
  {
    name: 'Voltix Nova 5G Smartphone',
    category: 'smartphones',
    brand: 'voltix',
    icon: 'Smartphone',
    short: '6.6" 120 Hz display, 50 MP camera and a 5000 mAh battery.',
    highlights: [
      '6.6-inch FHD+ 120 Hz display',
      '50 MP dual rear camera',
      '5000 mAh battery with 33 W charging',
      '5G ready with dual SIM',
    ],
    specs: [
      ['Display', '6.6" FHD+, 120 Hz'],
      ['Processor', 'Octa-core 2.2 GHz'],
      ['Rear camera', '50 MP + 2 MP'],
      ['Front camera', '16 MP'],
      ['Battery', '5000 mAh'],
      ['Charging', '33 W wired'],
      ['Network', '5G / 4G LTE'],
    ],
    variants: [
      v(
        'Midnight Blue / 6 GB + 128 GB',
        { Colour: 'Midnight Blue', Storage: '6 GB + 128 GB' },
        17999,
        13999,
        40,
      ),
      v(
        'Midnight Blue / 8 GB + 256 GB',
        { Colour: 'Midnight Blue', Storage: '8 GB + 256 GB' },
        20999,
        16499,
        25,
      ),
      v(
        'Sunset Orange / 6 GB + 128 GB',
        { Colour: 'Sunset Orange', Storage: '6 GB + 128 GB' },
        17999,
        13999,
        3,
      ),
    ],
    tax: 18,
    hsn: '8517',
    sold: 420,
    daysAgo: 60,
    featured: true,
    warranty: '1 year manufacturer warranty on the device, 6 months on accessories.',
  },
  {
    name: 'Voltix Lite 4G Smartphone',
    category: 'smartphones',
    brand: 'voltix',
    icon: 'Smartphone',
    short: 'Reliable everyday phone with a big battery.',
    highlights: [
      '6.5-inch HD+ display',
      '13 MP AI camera',
      '5000 mAh battery',
      'Expandable storage up to 512 GB',
    ],
    specs: [
      ['Display', '6.5" HD+'],
      ['Rear camera', '13 MP'],
      ['Battery', '5000 mAh'],
      ['Memory', '4 GB + 64 GB'],
    ],
    variants: [
      v('Graphite / 4 GB + 64 GB', { Colour: 'Graphite', Storage: '4 GB + 64 GB' }, 9999, 7499, 60),
    ],
    tax: 18,
    hsn: '8517',
    sold: 310,
    daysAgo: 120,
    warranty: '1 year manufacturer warranty.',
  },
  {
    name: 'Voltix Nova Pro 5G Smartphone',
    category: 'smartphones',
    brand: 'voltix',
    icon: 'Smartphone',
    short: 'AMOLED display, 108 MP camera and 67 W fast charging.',
    highlights: [
      '6.7-inch AMOLED, 120 Hz',
      '108 MP main camera with OIS',
      '67 W fast charging',
      'In-display fingerprint sensor',
    ],
    specs: [
      ['Display', '6.7" AMOLED, 120 Hz'],
      ['Rear camera', '108 MP + 8 MP + 2 MP'],
      ['Battery', '5000 mAh'],
      ['Charging', '67 W'],
    ],
    variants: [
      v(
        'Pearl White / 8 GB + 256 GB',
        { Colour: 'Pearl White', Storage: '8 GB + 256 GB' },
        29999,
        24999,
        12,
      ),
      v(
        'Obsidian Black / 12 GB + 256 GB',
        { Colour: 'Obsidian Black', Storage: '12 GB + 256 GB' },
        32999,
        27499,
        0,
      ),
    ],
    tax: 18,
    hsn: '8517',
    sold: 95,
    daysAgo: 10,
    featured: true,
    warranty: '1 year manufacturer warranty.',
  },
  {
    name: 'Voltix Tab 10 (Wi-Fi)',
    category: 'tablets',
    brand: 'voltix',
    icon: 'Tablet',
    short: '10.4" 2K display tablet for study and streaming.',
    highlights: [
      '10.4-inch 2K display',
      'Quad speakers',
      '7040 mAh battery',
      'Kids mode with parental controls',
    ],
    specs: [
      ['Display', '10.4" 2K'],
      ['Memory', '4 GB + 64 GB'],
      ['Battery', '7040 mAh'],
      ['Connectivity', 'Wi-Fi 5, Bluetooth 5.1'],
    ],
    variants: [
      v('Grey / 4 GB + 64 GB', { Colour: 'Grey', Storage: '4 GB + 64 GB' }, 19999, 14999, 18),
    ],
    tax: 18,
    hsn: '8471',
    sold: 64,
    daysAgo: 90,
    warranty: '1 year manufacturer warranty.',
  },
  // ---------------------------------------------------------------- audio
  {
    name: 'Aurora Sound Pods Air True Wireless Earbuds',
    category: 'earbuds',
    brand: 'aurora-sound',
    icon: 'Headset',
    short: 'Active noise cancellation with up to 40 hours of playback.',
    highlights: [
      'Active noise cancellation up to 30 dB',
      'Up to 40 hours with case',
      'Low-latency game mode',
      'IPX5 sweat resistance',
    ],
    specs: [
      ['Driver', '10 mm dynamic'],
      ['Playback', '8 h (earbuds) + 32 h (case)'],
      ['Bluetooth', '5.3'],
      ['Water resistance', 'IPX5'],
    ],
    variants: [
      v('Carbon Black', { Colour: 'Carbon Black' }, 4999, 1999, 120),
      v('Ice White', { Colour: 'Ice White' }, 4999, 1999, 45),
    ],
    tax: 18,
    hsn: '8518',
    sold: 860,
    daysAgo: 45,
    featured: true,
    warranty: '1 year warranty.',
  },
  {
    name: 'Aurora Sound Buds Lite Earbuds',
    category: 'earbuds',
    brand: 'aurora-sound',
    icon: 'Headset',
    short: 'Everyday wireless earbuds with clear calls.',
    highlights: [
      'Environmental noise cancellation for calls',
      'Up to 30 hours playback',
      'Type-C fast charging',
    ],
    specs: [
      ['Driver', '13 mm'],
      ['Playback', '30 h total'],
      ['Bluetooth', '5.3'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 2499, 999, 200)],
    tax: 18,
    hsn: '8518',
    sold: 540,
    daysAgo: 150,
    warranty: '1 year warranty.',
  },
  {
    name: 'Aurora Sound Studio 700 Wireless Headphones',
    category: 'headphones',
    brand: 'aurora-sound',
    icon: 'Headphones',
    short: 'Over-ear headphones with hybrid ANC and 60-hour battery.',
    highlights: [
      'Hybrid ANC with transparency mode',
      '60-hour battery life',
      'Memory-foam ear cushions',
      'Dual-device connection',
    ],
    specs: [
      ['Driver', '40 mm'],
      ['Battery', '60 h'],
      ['Bluetooth', '5.3 multipoint'],
      ['Weight', '240 g'],
    ],
    variants: [
      v('Midnight', { Colour: 'Midnight' }, 9999, 5999, 22),
      v('Sand', { Colour: 'Sand' }, 9999, 5999, 4),
    ],
    tax: 18,
    hsn: '8518',
    sold: 180,
    daysAgo: 20,
    featured: true,
    warranty: '1 year warranty.',
  },
  {
    name: 'Aurora Sound Wired Headphones with Mic',
    category: 'headphones',
    brand: 'aurora-sound',
    icon: 'Headphones',
    short: 'Comfortable wired headphones for calls and classes.',
    highlights: ['Inline mic with call controls', '3.5 mm universal jack', 'Foldable design'],
    specs: [
      ['Driver', '40 mm'],
      ['Cable', '1.2 m, tangle-free'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 1299, 649, 90)],
    tax: 18,
    hsn: '8518',
    sold: 230,
    daysAgo: 200,
  },
  {
    name: 'Aurora Sound Boom 20 Bluetooth Speaker',
    category: 'speakers',
    brand: 'aurora-sound',
    icon: 'Speaker',
    short: '20 W portable speaker, waterproof, 12-hour battery.',
    highlights: [
      '20 W stereo sound with deep bass',
      'IPX7 waterproof',
      '12-hour battery',
      'Pair two speakers for party mode',
    ],
    specs: [
      ['Output', '20 W'],
      ['Battery', '12 h'],
      ['Water resistance', 'IPX7'],
    ],
    variants: [
      v('Blue', { Colour: 'Blue' }, 4999, 2799, 35),
      v('Orange', { Colour: 'Orange' }, 4999, 2799, 30),
    ],
    tax: 18,
    hsn: '8518',
    sold: 150,
    daysAgo: 75,
    warranty: '1 year warranty.',
  },
  {
    name: 'Aurora Sound Soundbar 120 W',
    category: 'speakers',
    brand: 'aurora-sound',
    icon: 'Speaker',
    short: '2.1-channel soundbar with wired subwoofer.',
    highlights: ['120 W output', 'Wired subwoofer', 'HDMI ARC, optical and Bluetooth'],
    specs: [
      ['Output', '120 W'],
      ['Channels', '2.1'],
      ['Inputs', 'HDMI ARC, Optical, AUX, USB, Bluetooth'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 12999, 7999, 0)],
    tax: 18,
    hsn: '8518',
    sold: 40,
    daysAgo: 5,
  },
  // ---------------------------------------------------------------- wearables & accessories
  {
    name: 'PulseFit Active Smartwatch',
    category: 'smartwatches',
    brand: 'pulsefit',
    icon: 'Watch',
    short: '1.8" AMOLED, Bluetooth calling and 100+ sports modes.',
    highlights: [
      '1.8-inch AMOLED always-on display',
      'Bluetooth calling',
      'Heart-rate, SpO2 and sleep tracking',
      '7-day battery',
    ],
    specs: [
      ['Display', '1.8" AMOLED'],
      ['Battery', 'Up to 7 days'],
      ['Water resistance', 'IP68'],
    ],
    variants: [
      v('Black Strap', { Colour: 'Black' }, 6999, 2499, 70),
      v('Rose Gold Strap', { Colour: 'Rose Gold' }, 6999, 2699, 8),
    ],
    tax: 18,
    hsn: '8517',
    sold: 610,
    daysAgo: 35,
    featured: true,
    warranty: '1 year warranty.',
  },
  {
    name: 'PulseFit Band 3 Fitness Tracker',
    category: 'smartwatches',
    brand: 'pulsefit',
    icon: 'Watch',
    short: 'Slim fitness band with 14-day battery.',
    highlights: ['Step, heart-rate and sleep tracking', '14-day battery', '5 ATM water resistance'],
    specs: [
      ['Display', '1.1" colour'],
      ['Battery', '14 days'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 2999, 1299, 110)],
    tax: 18,
    hsn: '8517',
    sold: 290,
    daysAgo: 160,
  },
  {
    name: 'Voltix PowerMax 20000 mAh Power Bank',
    category: 'power-banks',
    brand: 'voltix',
    icon: 'BatteryCharging',
    short: '22.5 W fast charging, charges three devices at once.',
    highlights: [
      '20000 mAh capacity',
      '22.5 W fast charging',
      'Two USB-A + one USB-C port',
      'BIS certified',
    ],
    specs: [
      ['Capacity', '20000 mAh'],
      ['Output', '22.5 W max'],
      ['Ports', '2 × USB-A, 1 × USB-C'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 3499, 1499, 150)],
    tax: 18,
    hsn: '8507',
    sold: 700,
    daysAgo: 100,
  },
  {
    name: 'Voltix 33 W USB-C Fast Charger with Cable',
    category: 'chargers-cables',
    brand: 'voltix',
    icon: 'Cable',
    short: 'Compact 33 W charger with a 1 m USB-C cable.',
    highlights: ['33 W PD fast charging', 'Includes 1 m USB-C cable', 'Over-voltage protection'],
    specs: [
      ['Output', '33 W'],
      ['Cable', '1 m USB-C to USB-C'],
    ],
    variants: [v('White', { Colour: 'White' }, 1499, 699, 180)],
    tax: 18,
    hsn: '8504',
    sold: 380,
    daysAgo: 80,
  },
  {
    name: 'Voltix Braided USB-C Cable (1.5 m)',
    category: 'chargers-cables',
    brand: 'voltix',
    icon: 'Cable',
    short: 'Durable nylon-braided fast-charging cable.',
    highlights: ['60 W fast charging', 'Nylon braided, 10,000+ bends', 'Data transfer 480 Mbps'],
    specs: [
      ['Length', '1.5 m'],
      ['Max power', '60 W'],
    ],
    variants: [v('Grey', { Colour: 'Grey' }, 599, 249, 300)],
    tax: 18,
    hsn: '8544',
    sold: 520,
    daysAgo: 25,
  },
  // ---------------------------------------------------------------- fashion
  {
    name: 'Urban Stride Men’s Cotton Crew T-Shirt',
    category: 'mens-t-shirts',
    brand: 'urban-stride',
    icon: 'Shirt',
    short: '100% combed cotton, regular fit.',
    highlights: ['100% combed cotton, 180 GSM', 'Regular fit', 'Pre-shrunk, machine washable'],
    specs: [
      ['Fabric', '100% cotton'],
      ['Fit', 'Regular'],
      ['Care', 'Machine wash cold'],
    ],
    variants: [
      v('Navy / M', { Colour: 'Navy', Size: 'M' }, 799, 399, 40),
      v('Navy / L', { Colour: 'Navy', Size: 'L' }, 799, 399, 35),
      v('Navy / XL', { Colour: 'Navy', Size: 'XL' }, 799, 399, 20),
      v('White / M', { Colour: 'White', Size: 'M' }, 799, 399, 30),
      v('White / L', { Colour: 'White', Size: 'L' }, 799, 399, 0),
    ],
    tax: 5,
    hsn: '6109',
    sold: 480,
    daysAgo: 70,
    returnDays: 15,
  },
  {
    name: 'Urban Stride Men’s Polo T-Shirt',
    category: 'mens-t-shirts',
    brand: 'urban-stride',
    icon: 'Shirt',
    short: 'Pique cotton polo with a classic collar.',
    highlights: ['Cotton pique fabric', 'Two-button placket', 'Ribbed collar and cuffs'],
    specs: [
      ['Fabric', '100% cotton pique'],
      ['Fit', 'Slim'],
    ],
    variants: [
      v('Olive / M', { Colour: 'Olive', Size: 'M' }, 1199, 649, 25),
      v('Olive / L', { Colour: 'Olive', Size: 'L' }, 1199, 649, 25),
    ],
    tax: 5,
    hsn: '6105',
    sold: 120,
    daysAgo: 12,
    returnDays: 15,
  },
  {
    name: 'Urban Stride Men’s Running Shoes',
    category: 'mens-shoes',
    brand: 'urban-stride',
    icon: 'Footprints',
    short: 'Lightweight mesh running shoes with cushioned sole.',
    highlights: ['Breathable knit mesh upper', 'EVA cushioned midsole', 'Anti-skid rubber outsole'],
    specs: [
      ['Upper', 'Knit mesh'],
      ['Sole', 'EVA + rubber'],
      ['Closure', 'Lace-up'],
    ],
    variants: [
      v('Grey / UK 7', { Colour: 'Grey', Size: 'UK 7' }, 2999, 1499, 14),
      v('Grey / UK 8', { Colour: 'Grey', Size: 'UK 8' }, 2999, 1499, 20),
      v('Grey / UK 9', { Colour: 'Grey', Size: 'UK 9' }, 2999, 1499, 16),
      v('Grey / UK 10', { Colour: 'Grey', Size: 'UK 10' }, 2999, 1499, 2),
    ],
    tax: 12,
    hsn: '6404',
    sold: 260,
    daysAgo: 55,
    returnDays: 15,
  },
  {
    name: 'Urban Stride Men’s Casual Sneakers',
    category: 'mens-shoes',
    brand: 'urban-stride',
    icon: 'Footprints',
    short: 'Minimal white sneakers for everyday wear.',
    highlights: ['Synthetic leather upper', 'Padded collar', 'Memory-foam insole'],
    specs: [
      ['Upper', 'Synthetic leather'],
      ['Sole', 'Rubber'],
    ],
    variants: [
      v('White / UK 8', { Colour: 'White', Size: 'UK 8' }, 2499, 1799, 10),
      v('White / UK 9', { Colour: 'White', Size: 'UK 9' }, 2499, 1799, 10),
    ],
    tax: 12,
    hsn: '6404',
    sold: 75,
    daysAgo: 8,
    returnDays: 15,
  },
  {
    name: 'Kavya Threads Women’s Printed Cotton Kurta',
    category: 'kurtas',
    brand: 'kavya-threads',
    icon: 'Shirt',
    short: 'Straight-fit block-print kurta in breathable cotton.',
    highlights: [
      'Pure cotton, hand block print',
      'Straight fit, calf length',
      'Three-quarter sleeves',
    ],
    specs: [
      ['Fabric', '100% cotton'],
      ['Length', 'Calf length'],
      ['Care', 'Hand wash'],
    ],
    variants: [
      v('Indigo / S', { Colour: 'Indigo', Size: 'S' }, 1499, 699, 20),
      v('Indigo / M', { Colour: 'Indigo', Size: 'M' }, 1499, 699, 30),
      v('Indigo / L', { Colour: 'Indigo', Size: 'L' }, 1499, 699, 18),
      v('Mustard / M', { Colour: 'Mustard', Size: 'M' }, 1499, 749, 12),
    ],
    tax: 5,
    hsn: '6204',
    sold: 390,
    daysAgo: 30,
    featured: true,
    returnDays: 15,
  },
  {
    name: 'Kavya Threads Women’s Anarkali Kurta Set',
    category: 'kurtas',
    brand: 'kavya-threads',
    icon: 'Shirt',
    short: 'Festive anarkali with dupatta and palazzo.',
    highlights: [
      'Rayon anarkali with gota work',
      'Includes palazzo and dupatta',
      'Flared silhouette',
    ],
    specs: [
      ['Fabric', 'Rayon'],
      ['Set', 'Kurta, palazzo, dupatta'],
    ],
    variants: [
      v('Maroon / M', { Colour: 'Maroon', Size: 'M' }, 3999, 1899, 10),
      v('Maroon / L', { Colour: 'Maroon', Size: 'L' }, 3999, 1899, 6),
    ],
    tax: 5,
    hsn: '6204',
    sold: 140,
    daysAgo: 3,
    returnDays: 15,
  },
  {
    name: 'Kavya Threads Everyday Tote Handbag',
    category: 'handbags',
    brand: 'kavya-threads',
    icon: 'ShoppingBag',
    short: 'Spacious vegan-leather tote with laptop sleeve.',
    highlights: ['Fits 14-inch laptop', 'Vegan leather', 'Zip closure with inner pockets'],
    specs: [
      ['Material', 'PU vegan leather'],
      ['Dimensions', '38 × 30 × 12 cm'],
    ],
    variants: [
      v('Tan', { Colour: 'Tan' }, 2999, 1299, 25),
      v('Black', { Colour: 'Black' }, 2999, 1299, 25),
    ],
    tax: 18,
    hsn: '4202',
    sold: 170,
    daysAgo: 65,
    returnDays: 15,
  },
  // ---------------------------------------------------------------- home & kitchen
  {
    name: 'Rasoi Pro 750 W Mixer Grinder',
    category: 'kitchen-appliances',
    brand: 'rasoi-pro',
    icon: 'Blend',
    short: '750 W motor with three stainless steel jars.',
    highlights: [
      '750 W copper motor',
      '3 stainless steel jars',
      'Overload protection',
      '2-year motor warranty',
    ],
    specs: [
      ['Power', '750 W'],
      ['Jars', '1.5 L, 1 L, 0.4 L'],
      ['Speed', '3 + pulse'],
    ],
    variants: [v('White & Blue', { Colour: 'White & Blue' }, 5499, 2999, 45)],
    tax: 18,
    hsn: '8509',
    sold: 350,
    daysAgo: 110,
    featured: true,
    warranty: '2 years on motor, 1 year on product.',
  },
  {
    name: 'Rasoi Pro 1.5 L Electric Kettle',
    category: 'kitchen-appliances',
    brand: 'rasoi-pro',
    icon: 'CupSoda',
    short: 'Stainless steel kettle with auto shut-off.',
    highlights: [
      '1500 W fast boiling',
      'Auto shut-off and boil-dry protection',
      'Food-grade stainless steel',
    ],
    specs: [
      ['Capacity', '1.5 L'],
      ['Power', '1500 W'],
    ],
    variants: [v('Steel', { Colour: 'Steel' }, 1999, 849, 90)],
    tax: 18,
    hsn: '8516',
    sold: 420,
    daysAgo: 140,
    warranty: '1 year warranty.',
  },
  {
    name: 'Rasoi Pro 4.5 L Air Fryer',
    category: 'kitchen-appliances',
    brand: 'rasoi-pro',
    icon: 'Microwave',
    short: 'Crispy snacks with up to 85% less oil.',
    highlights: [
      '4.5 L basket',
      '8 preset menus',
      'Digital touch controls',
      'Dishwasher-safe basket',
    ],
    specs: [
      ['Capacity', '4.5 L'],
      ['Power', '1400 W'],
      ['Temperature', '80–200 °C'],
    ],
    variants: [v('Black', { Colour: 'Black' }, 8999, 4499, 16)],
    tax: 18,
    hsn: '8516',
    sold: 210,
    daysAgo: 18,
    featured: true,
    warranty: '1 year warranty.',
  },
  {
    name: 'Rasoi Pro Tri-Ply Stainless Steel Kadai with Lid',
    category: 'cookware',
    brand: 'rasoi-pro',
    icon: 'CookingPot',
    short: 'Even heating tri-ply kadai, induction friendly.',
    highlights: ['Tri-ply stainless steel', 'Works on gas and induction', 'Toughened glass lid'],
    specs: [
      ['Diameter', '24 cm'],
      ['Capacity', '2.8 L'],
    ],
    variants: [
      v('24 cm', { Size: '24 cm' }, 2999, 1649, 30),
      v('28 cm', { Size: '28 cm' }, 3499, 1999, 20),
    ],
    tax: 12,
    hsn: '7323',
    sold: 190,
    daysAgo: 95,
  },
  {
    name: 'Rasoi Pro Non-Stick Cookware Set (3 pcs)',
    category: 'cookware',
    brand: 'rasoi-pro',
    icon: 'CookingPot',
    short: 'Tawa, frying pan and kadai with PFOA-free coating.',
    highlights: ['PFOA-free non-stick coating', 'Induction base', 'Heat-resistant handles'],
    specs: [['Pieces', 'Tawa 28 cm, Fry pan 24 cm, Kadai 24 cm']],
    variants: [v('Red', { Colour: 'Red' }, 3999, 1799, 0)],
    tax: 12,
    hsn: '7615',
    sold: 88,
    daysAgo: 130,
  },
  {
    name: 'NestCraft Handwoven Cotton Cushion Covers (Set of 5)',
    category: 'home-decor',
    brand: 'nestcraft',
    icon: 'Sofa',
    short: 'Handwoven covers that brighten any room.',
    highlights: ['Handwoven cotton', 'Concealed zip', 'Fits 16 × 16 inch cushions'],
    specs: [
      ['Size', '16 × 16 in'],
      ['Material', '100% cotton'],
    ],
    variants: [
      v('Teal Mix', { Colour: 'Teal Mix' }, 1499, 599, 50),
      v('Earth Mix', { Colour: 'Earth Mix' }, 1499, 599, 40),
    ],
    tax: 12,
    hsn: '6304',
    sold: 160,
    daysAgo: 50,
    returnDays: 10,
  },
  {
    name: 'NestCraft Brass Finish Table Lamp',
    category: 'home-decor',
    brand: 'nestcraft',
    icon: 'Lamp',
    short: 'Warm reading light with fabric shade.',
    highlights: ['Brass-finish metal base', 'Linen fabric shade', 'E27 holder (bulb not included)'],
    specs: [
      ['Height', '42 cm'],
      ['Holder', 'E27'],
    ],
    variants: [v('Brass / Ivory', { Colour: 'Brass / Ivory' }, 2999, 1599, 9)],
    tax: 18,
    hsn: '9405',
    sold: 45,
    daysAgo: 6,
    returnDays: 10,
  },
  // ---------------------------------------------------------------- beauty
  {
    name: 'Sattva Naturals Vitamin C Face Serum (30 ml)',
    category: 'skincare',
    brand: 'sattva-naturals',
    icon: 'Droplet',
    short: '10% vitamin C for brighter-looking skin.',
    highlights: [
      '10% vitamin C with hyaluronic acid',
      'Lightweight, non-sticky',
      'Dermatologically tested',
    ],
    specs: [
      ['Volume', '30 ml'],
      ['Skin type', 'All skin types'],
    ],
    variants: [v('30 ml', { Size: '30 ml' }, 699, 489, 140)],
    tax: 18,
    hsn: '3304',
    sold: 640,
    daysAgo: 40,
    featured: true,
    returnDays: 0,
  },
  {
    name: 'Sattva Naturals Aloe & Neem Face Wash (150 ml)',
    category: 'skincare',
    brand: 'sattva-naturals',
    icon: 'Droplet',
    short: 'Gentle daily cleanser for oily skin.',
    highlights: ['Aloe vera and neem extracts', 'Soap-free', 'Suitable for daily use'],
    specs: [['Volume', '150 ml']],
    variants: [
      v('150 ml', { Size: '150 ml' }, 299, 219, 200),
      v('300 ml', { Size: '300 ml' }, 549, 379, 80),
    ],
    tax: 18,
    hsn: '3401',
    sold: 900,
    daysAgo: 180,
    returnDays: 0,
  },
  {
    name: 'Sattva Naturals SPF 50 Sunscreen (50 g)',
    category: 'skincare',
    brand: 'sattva-naturals',
    icon: 'Sun',
    short: 'Broad-spectrum PA+++ with no white cast.',
    highlights: ['SPF 50, PA+++', 'No white cast', 'Water resistant up to 80 minutes'],
    specs: [['Net weight', '50 g']],
    variants: [v('50 g', { Size: '50 g' }, 499, 399, 5)],
    tax: 18,
    hsn: '3304',
    sold: 310,
    daysAgo: 14,
    returnDays: 0,
  },
  {
    name: 'Sattva Naturals Onion & Bhringraj Hair Oil (200 ml)',
    category: 'hair-care',
    brand: 'sattva-naturals',
    icon: 'Wind',
    short: 'Nourishing oil for stronger-looking hair.',
    highlights: ['Onion and bhringraj extracts', 'Non-sticky formula', 'For all hair types'],
    specs: [['Volume', '200 ml']],
    variants: [v('200 ml', { Size: '200 ml' }, 449, 299, 120)],
    tax: 18,
    hsn: '3305',
    sold: 450,
    daysAgo: 85,
    returnDays: 0,
  },
  {
    name: 'Sattva Naturals Hibiscus Shampoo (340 ml)',
    category: 'hair-care',
    brand: 'sattva-naturals',
    icon: 'Wind',
    short: 'Sulphate-free shampoo for soft, manageable hair.',
    highlights: ['Sulphate- and paraben-free', 'Hibiscus and amla', 'Gentle for daily use'],
    specs: [['Volume', '340 ml']],
    variants: [v('340 ml', { Size: '340 ml' }, 499, 349, 70)],
    tax: 18,
    hsn: '3305',
    sold: 205,
    daysAgo: 22,
    returnDays: 0,
  },
  // ---------------------------------------------------------------- sports
  {
    name: 'Tarang Sports Anti-Slip Yoga Mat (6 mm)',
    category: 'yoga',
    brand: 'tarang-sports',
    icon: 'PersonStanding',
    short: 'Extra-grip TPE mat with carry strap.',
    highlights: ['6 mm eco-friendly TPE', 'Double-sided anti-slip texture', 'Carry strap included'],
    specs: [
      ['Size', '183 × 61 cm'],
      ['Thickness', '6 mm'],
      ['Material', 'TPE'],
    ],
    variants: [
      v('Purple', { Colour: 'Purple' }, 1499, 699, 60),
      v('Teal', { Colour: 'Teal' }, 1499, 699, 60),
    ],
    tax: 12,
    hsn: '9506',
    sold: 330,
    daysAgo: 70,
    featured: true,
  },
  {
    name: 'Tarang Sports Yoga Blocks (Pair)',
    category: 'yoga',
    brand: 'tarang-sports',
    icon: 'PersonStanding',
    short: 'High-density EVA blocks for support and alignment.',
    highlights: ['High-density EVA foam', 'Bevelled edges', 'Lightweight and washable'],
    specs: [['Size', '23 × 15 × 7.5 cm']],
    variants: [v('Blue', { Colour: 'Blue' }, 799, 399, 45)],
    tax: 12,
    hsn: '9506',
    sold: 85,
    daysAgo: 16,
  },
  {
    name: 'Tarang Sports Adjustable Dumbbell Set (20 kg)',
    category: 'fitness-equipment',
    brand: 'tarang-sports',
    icon: 'Dumbbell',
    short: 'Home gym set with plates, rods and spinlock collars.',
    highlights: [
      '20 kg total weight',
      'Two 14-inch rods with spinlock collars',
      'PVC-coated plates',
    ],
    specs: [
      ['Total weight', '20 kg'],
      ['Rods', '2 × 14 inch'],
    ],
    variants: [v('20 kg', { Weight: '20 kg' }, 3999, 2199, 12)],
    tax: 18,
    hsn: '9506',
    sold: 140,
    daysAgo: 100,
  },
  {
    name: 'Tarang Sports Resistance Bands Set',
    category: 'fitness-equipment',
    brand: 'tarang-sports',
    icon: 'Dumbbell',
    short: 'Five resistance levels with handles and door anchor.',
    highlights: [
      '5 stackable bands (10–50 lb)',
      'Foam handles and ankle straps',
      'Door anchor and travel pouch',
    ],
    specs: [
      ['Levels', '5'],
      ['Material', 'Natural latex'],
    ],
    variants: [v('Multicolour', { Colour: 'Multicolour' }, 1299, 599, 0)],
    tax: 18,
    hsn: '9506',
    sold: 60,
    daysAgo: 28,
  },
  {
    name: 'PulseFit Smart Skipping Rope',
    category: 'fitness-equipment',
    brand: 'pulsefit',
    icon: 'Activity',
    short: 'Counts jumps and calories on a built-in display.',
    highlights: [
      'LCD counter for jumps, time and calories',
      'Adjustable length',
      'Weighted handles',
    ],
    specs: [['Length', 'Adjustable up to 3 m']],
    variants: [v('Black', { Colour: 'Black' }, 999, 549, 40)],
    tax: 18,
    hsn: '9506',
    sold: 70,
    daysAgo: 2,
  },
];

export const DEMO_BANNERS = [
  {
    title: 'Smart Shopping, Better Living',
    subtitle: 'Top picks across electronics, fashion and home — delivered fast across India.',
    ctaLabel: 'Shop best sellers',
    link: '/best-sellers',
    placement: 'HOME_HERO' as const,
    theme: 'NAVY' as const,
    priority: 20,
  },
  {
    title: 'Deals up to 60% off',
    subtitle: 'Earbuds, smartwatches and kitchen essentials at their lowest prices.',
    ctaLabel: 'See today’s deals',
    link: '/deals',
    placement: 'HOME_HERO' as const,
    theme: 'PRIMARY' as const,
    priority: 10,
  },
  {
    title: 'Audio days',
    subtitle: 'Earbuds from ₹999',
    ctaLabel: 'Shop audio',
    link: '/category/audio',
    placement: 'HOME_PROMO' as const,
    theme: 'PRIMARY' as const,
    priority: 30,
  },
  {
    title: 'New arrivals',
    subtitle: 'Fresh styles this week',
    ctaLabel: 'Explore',
    link: '/new-arrivals',
    placement: 'HOME_PROMO' as const,
    theme: 'NAVY' as const,
    priority: 20,
  },
  {
    title: 'Kitchen upgrade',
    subtitle: 'Appliances from ₹849',
    ctaLabel: 'Shop kitchen',
    link: '/category/kitchen-appliances',
    placement: 'HOME_PROMO' as const,
    theme: 'ACCENT' as const,
    priority: 10,
  },
];

export const DEMO_HOME_SECTIONS = [
  {
    title: 'Best sellers',
    subtitle: 'Most loved by SeShaKart shoppers',
    source: 'BEST_SELLERS' as const,
  },
  { title: 'Deals of the day', subtitle: 'Big savings, limited stock', source: 'DEALS' as const },
  { title: 'New arrivals', subtitle: 'Just landed', source: 'NEW_ARRIVALS' as const },
  {
    title: 'Top picks in audio',
    subtitle: 'Earbuds, headphones and speakers',
    source: 'CATEGORY' as const,
    category: 'audio',
  },
  { title: 'Featured products', subtitle: 'Handpicked by our team', source: 'FEATURED' as const },
];
